notifications:
  email: false

language: python

sudo: false

env:
  matrix:
    - TOXENV=flake8
    - TOXENV=py27-1.11
    - TOXENV=py34-1.11
    - TOXENV=py36-1.11
    - TOXENV=py37-1.11    

install:
  - pip install tox
script:
  - tox
