dist: xenial

notifications:
  email: false

language: python
python: 3.6

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-1.11
env:
  matrix:
    - TOXENV=flake8
    - TOXENV=py36-1.11
    - TOXENV=py36-2.2
    - TOXENV=py36-3.0
    - TOXENV=py36-3.1

install:
  - pip install tox
script:
  - tox
