notifications:
  email: false

language: python
cache: pip

sudo: false

matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=py27-1.11
    - python: 3.4
      env: TOXENV=py34-1.11
    - python: 3.4
      env: TOXENV=py34-2.0
    - python: 3.6
      env: TOXENV=py36-1.11
    - python: 3.6
      env: TOXENV=py36-2.0
    - python: 3.6
      env: TOXENV=py36-2.1
    - python: 3.7
      env: TOXENV=py37-1.11
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-2.0
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-2.1
      dist: xenial
      sudo: true
      
install:
  - pip install tox
script:
  - tox
